"""The generated files that are not Dart.

pubspec, the Android manifest, Gradle properties, MainActivity, the launch
screen drawables, and the iOS usage descriptions.

Kept apart from the Dart emitters because these are the files a Flutter upgrade
is most likely to change the shape of, and finding them should not mean
scrolling past a thousand lines of widget code first.
"""

from __future__ import annotations

from html import escape

from ..config import AppConfig
from . import push
from .common import DEPENDENCIES, _host_of, deep_link_scheme, project_name


# ── pubspec ──────────────────────────────────────────────────────────────


def pubspec(
    config: AppConfig,
    splash_asset: str | None = None,
    icon_asset: str | None = None,
    offline_asset: str | None = None,
) -> str:
    features = set(config.features)
    lines = [
        f"name: {project_name(config)}",
        "description: Generated by Cissy.",
        "publish_to: none",
        f"version: {config.version_name}+{config.version_code}",
        "",
        "environment:",
        "  sdk: ^3.9.0",
        "",
        "dependencies:",
        "  flutter:",
        "    sdk: flutter",
        f"  flutter_inappwebview: {DEPENDENCIES['flutter_inappwebview']}",
        f"  url_launcher: {DEPENDENCIES['url_launcher']}",
    ]
    if "Native sharing" in features:
        lines.append(f"  share_plus: {DEPENDENCIES['share_plus']}")
    if "Location" in features:
        lines.append(f"  geolocator: {DEPENDENCIES['geolocator']}")
    if "Downloads" in features:
        lines.append(f"  path_provider: {DEPENDENCIES['path_provider']}")
        lines.append(f"  open_filex: {DEPENDENCIES['open_filex']}")
    if "Deep links" in features:
        lines.append(f"  app_links: {DEPENDENCIES['app_links']}")
    if config.offline_fallback_enabled:
        lines.append(f"  connectivity_plus: {DEPENDENCIES['connectivity_plus']}")
    if config.push_enabled:
        for name, version in push.PUSH_DEPENDENCIES.items():
            lines.append(f"  {name}: {version}")
    # Push stores which categories the user chose.
    if config.push_enabled:
        lines.append(f"  shared_preferences: {DEPENDENCIES['shared_preferences']}")

    lines += [
        "",
        "dev_dependencies:",
        "  flutter_test:",
        "    sdk: flutter",
        "  flutter_lints: ^5.0.0",
    ]
    if icon_asset:
        lines.append(f"  flutter_launcher_icons: {DEPENDENCIES['flutter_launcher_icons']}")

    lines += [
        "",
        "flutter:",
        "  uses-material-design: true",
    ]
    # The icon is copied in for flutter_launcher_icons, which reads it at build
    # time from disk. The icon splash draws it at run time, so on that setting
    # it has to be a declared asset as well or Image.asset finds nothing.
    icon_splash = config.splash_style != "image" and icon_asset
    bundled = [
        asset
        for asset in (splash_asset, offline_asset, icon_asset if icon_splash else None)
        if asset
    ]
    if bundled:
        lines += ["  assets:"] + [f"    - {asset}" for asset in bundled]

    if icon_asset:
        # Android reads the launcher icon from five mipmap densities and iOS
        # from about fifteen sizes in an appiconset. Generating those needs an
        # image library, which this server does not have - so the sizes are
        # produced by flutter_launcher_icons on the build machine instead,
        # where the Dart toolchain already is.
        lines += [
            "",
            "flutter_launcher_icons:",
            "  android: true",
            "  ios: true",
            f"  image_path: {icon_asset}",
            "  min_sdk_android: 21",
            # iOS rejects an icon with an alpha channel, and a logo exported
            # with a transparent background is the normal case.
            "  remove_alpha_ios: true",
        ]
    return "\n".join(lines) + "\n"


# ── android ──────────────────────────────────────────────────────────────


def android_manifest(config: AppConfig) -> str:
    features = set(config.features)
    label = escape(config.display_name, quote=True)
    host = _host_of(config.website_url)

    permissions = ['    <uses-permission android:name="android.permission.INTERNET" />']
    if "Camera" in features:
        permissions.append(
            '    <uses-permission android:name="android.permission.CAMERA" />'
        )
    if "Location" in features:
        permissions.append(
            '    <uses-permission '
            'android:name="android.permission.ACCESS_COARSE_LOCATION" />'
        )
        permissions.append(
            '    <uses-permission '
            'android:name="android.permission.ACCESS_FINE_LOCATION" />'
        )

    deep_link_filter = ""
    if "Deep links" in features and host:
        deep_link_filter = f"""
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="https" android:host="{host}"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="{deep_link_scheme(config)}"/>
            </intent-filter>"""

    if config.push_enabled:
        # Android 13 and later. Without it the app never gets to ask, and
        # every notification is dropped silently.
        permissions.append(
            '    <uses-permission '
            'android:name="android.permission.POST_NOTIFICATIONS" />'
        )

    # Where a notification lands when the app has never been opened, so the
    # system has no channel from the app itself to put it in. Declared here as
    # well as created in Dart because that case happens before any Dart runs.
    push_meta = ""
    if config.push_enabled:
        push_meta = f"""
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="{push.CHANNEL_ID}" />"""

    cleartext = "true" if not config.require_https else "false"

    return f"""<manifest xmlns:android="http://schemas.android.com/apk/res/android">
{chr(10).join(permissions)}
    <application
        android:label="{label}"
        android:name="${{applicationName}}"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="{cleartext}">
        <activity
            android:name="{config.android_package_id}.MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:taskAffinity=""
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>{deep_link_filter}
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />{push_meta}
    </application>
</manifest>
"""


def gradle_properties() -> str:
    """Gradle settings tuned for a small, occasionally-used build box.

    The daemon holds well over a gigabyte between builds, which is wasted on a
    server that builds twice a week and has 4 GB to work with. Turning it off
    costs about twenty seconds of JVM startup per build.
    """
    return (
        "org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m\n"
        "org.gradle.daemon=false\n"
        "org.gradle.parallel=false\n"
        "android.useAndroidX=true\n"
        "android.enableJetifier=true\n"
    )


def main_activity(config: AppConfig) -> str:
    return f"""package {config.android_package_id}

import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity()
"""


# ── the launch screen ────────────────────────────────────────────────────

# The resource name the uploaded splash is copied in under. Fixed rather than
# derived from the upload's filename, because Android resource names allow
# only lowercase letters, digits and underscores.
SPLASH_DRAWABLE = "cissy_splash"


def launch_background(has_splash: bool, colour: str = "") -> str:
    """The window Android draws between tapping the icon and Flutter's first
    frame.

    With a splash image this IS the splash, so the app opens straight into it
    with no white flash in between. `fill` gravity because an XML bitmap
    cannot centre-crop; the in-app splash widget (BoxFit.cover) takes over on
    the first Flutter frame, so any stretch lasts a fraction of a second.

    With the icon splash there is no image to draw here - the icon is a Flutter
    widget and Flutter has not started yet - so the window is the splash's own
    background colour. That makes the seam invisible: the plain colour Android
    paints is the same colour the first Flutter frame paints under the icon.
    """
    if not has_splash:
        if colour:
            return f"""<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/cissy_splash_background" />
</layer-list>
"""
        # The Flutter scaffold's own default.
        return """<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/white" />
</layer-list>
"""
    return f"""<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <bitmap
            android:gravity="fill"
            android:src="@drawable/{SPLASH_DRAWABLE}" />
    </item>
</layer-list>
"""


def splash_colour_resource(colour: str) -> str:
    """The splash background, as an Android colour resource.

    A separate file rather than a literal in the layer-list, because the same
    name is overridden in values-night and a literal cannot be.
    """
    return f"""<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="cissy_splash_background">{colour}</color>
</resources>
"""


def splash_icon_drawable() -> str:
    """A fully transparent drawable for the Android 12+ system splash icon.

    From Android 12 the OS itself draws a launch screen - by default the app
    icon centred on a plain background - before the app process even starts,
    and no app can opt out of that phase. What it CAN do is hand the phase a
    transparent icon, which turns "the icon flashes, then the splash" into
    "a plain surface, then the splash".
    """
    return """<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="@android:color/transparent" />
</shape>
"""


def styles_v31(*, night: bool, colour: str = "") -> str:
    """LaunchTheme for Android 12+, where the system splash exists.

    Only LaunchTheme is overridden; NormalTheme still comes from the
    scaffold's values/styles.xml. windowBackground stays the splash image so
    the moment the system phase ends the splash is already on screen.
    """
    parent = "Theme.Black.NoTitleBar" if night else "Theme.Light.NoTitleBar"
    # The system splash's own background. With the icon splash it is the chosen
    # colour, so the Android 12 phase, the launch window and the first Flutter
    # frame are all the same colour and the app appears to open in one piece.
    background = colour or ("@android:color/black" if night else "@android:color/white")
    return f"""<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="@android:style/{parent}">
        <item name="android:windowSplashScreenBackground">{background}</item>
        <item name="android:windowSplashScreenAnimatedIcon">@drawable/{SPLASH_DRAWABLE}_icon</item>
        <item name="android:windowBackground">@drawable/launch_background</item>
        <item name="android:forceDarkAllowed">false</item>
    </style>
</resources>
"""


# ── ios ──────────────────────────────────────────────────────────────────


def ios_usage_descriptions(config: AppConfig) -> dict[str, str]:
    """Info.plist reasons for every permission the app can request.

    A missing one is not a warning - iOS terminates the app the moment the
    permission is requested, and App Store review rejects the build.
    """
    features = set(config.features)
    values: dict[str, str] = {}
    if "Camera" in features:
        values["NSCameraUsageDescription"] = config.permission_description("camera")
    if "Camera" in features or "File upload" in features:
        values["NSPhotoLibraryUsageDescription"] = config.permission_description(
            "photos"
        )
    if "Location" in features:
        values["NSLocationWhenInUseUsageDescription"] = config.permission_description(
            "location"
        )
    return values
