"""The generated app's source code.

Ported from the desktop builder's `GeneratedAppTemplate`. This is the actual
product — everything else in this server exists to run `flutter build` over what
comes out of here.

Written as plain string concatenation rather than a templating engine, because
Dart uses `$` for interpolation and `{}` for blocks, and every engine wants one
or both of those. Values that come from user input go through `dart_string()`,
which produces a correctly escaped Dart literal.

Feature flags emit or omit whole blocks. Anything referenced by an emitted block
must itself be emitted, or the generated project fails its own lint run — the
`_load` and `_is_allowed_web_uri` conditions below exist for exactly that.
"""

from __future__ import annotations

import json
import re
from html import escape

from .config import AppConfig

# Pinned rather than floating: a generated project should build the same way in
# six months, and a surprise major version is not a debugging session anyone
# wants to have from a build log.
DEPENDENCIES = {
    "flutter_inappwebview": "^6.1.5",
    "url_launcher": "^6.3.2",
    "share_plus": "^11.1.0",
    "geolocator": "^14.0.2",
    "path_provider": "^2.1.5",
    "open_filex": "^4.7.0",
    "app_links": "^6.4.1",
    "flutter_launcher_icons": "^0.14.4",
}


def dart_string(value: object) -> str:
    """A Dart string literal. JSON's escaping rules are a subset of Dart's."""
    return json.dumps("" if value is None else str(value))


def deep_link_scheme(config: AppConfig) -> str:
    """A custom URL scheme derived from the app name.

    Schemes must start with a letter, so leading digits are stripped rather than
    producing something Android silently refuses to register.
    """
    value = re.sub(r"[^a-z0-9]+", "", config.display_name.strip().lower())
    value = re.sub(r"^[^a-z]+", "", value)
    return value or "cissyapp"


# Dart keywords that cannot be a package name. Short list because a package
# name is only ever the last segment of a validated package id.
_RESERVED = {"test", "async", "await", "class", "const", "new", "void", "is", "in"}


def project_name(config: AppConfig) -> str:
    """The pubspec package name — the last segment of the package id.

    Taken from the package id rather than the app name so that
    `flutter create --org <rest> --project-name <last>` produces exactly the
    configured applicationId and bundle id, with nothing left to patch
    afterwards.
    """
    segment = config.android_package_id.rsplit(".", 1)[-1]
    value = re.sub(r"[^a-z0-9_]+", "_", segment.lower()).strip("_")
    if not value or value[0].isdigit():
        value = f"app_{value}" if value else "cissy_app"
    return f"{value}_app" if value in _RESERVED else value


def organisation(config: AppConfig) -> str:
    """Everything before the last segment of the package id."""
    parts = config.android_package_id.rsplit(".", 1)
    return parts[0] if len(parts) == 2 else "com.cissytech"


# ── pubspec ──────────────────────────────────────────────────────────────


def pubspec(
    config: AppConfig,
    splash_asset: str | None = None,
    icon_asset: str | None = None,
) -> str:
    features = set(config.features)
    lines = [
        f"name: {project_name(config)}",
        "description: Generated by Cissy.",
        "publish_to: none",
        f"version: {config.version_name}+{config.version_code}",
        "",
        "environment:",
        "  sdk: ^3.9.0",
        "",
        "dependencies:",
        "  flutter:",
        "    sdk: flutter",
        f"  flutter_inappwebview: {DEPENDENCIES['flutter_inappwebview']}",
        f"  url_launcher: {DEPENDENCIES['url_launcher']}",
    ]
    if "Native sharing" in features:
        lines.append(f"  share_plus: {DEPENDENCIES['share_plus']}")
    if "Location" in features:
        lines.append(f"  geolocator: {DEPENDENCIES['geolocator']}")
    if "Downloads" in features:
        lines.append(f"  path_provider: {DEPENDENCIES['path_provider']}")
        lines.append(f"  open_filex: {DEPENDENCIES['open_filex']}")
    if "Deep links" in features:
        lines.append(f"  app_links: {DEPENDENCIES['app_links']}")

    lines += [
        "",
        "dev_dependencies:",
        "  flutter_test:",
        "    sdk: flutter",
        "  flutter_lints: ^5.0.0",
    ]
    if icon_asset:
        lines.append(f"  flutter_launcher_icons: {DEPENDENCIES['flutter_launcher_icons']}")

    lines += [
        "",
        "flutter:",
        "  uses-material-design: true",
    ]
    if splash_asset:
        lines += ["  assets:", f"    - {splash_asset}"]

    if icon_asset:
        # Android reads the launcher icon from five mipmap densities and iOS
        # from about fifteen sizes in an appiconset. Generating those needs an
        # image library, which this server does not have — so the sizes are
        # produced by flutter_launcher_icons on the build machine instead,
        # where the Dart toolchain already is.
        lines += [
            "",
            "flutter_launcher_icons:",
            "  android: true",
            "  ios: true",
            f"  image_path: {icon_asset}",
            "  min_sdk_android: 21",
            # iOS rejects an icon with an alpha channel, and a logo exported
            # with a transparent background is the normal case.
            "  remove_alpha_ios: true",
        ]
    return "\n".join(lines) + "\n"


# ── main.dart ────────────────────────────────────────────────────────────


def main_dart(config: AppConfig, splash_asset: str | None = None) -> str:
    features = set(config.features)
    has_share = "Native sharing" in features
    has_location = "Location" in features
    has_downloads = "Downloads" in features
    has_deep_links = "Deep links" in features
    has_pull_refresh = "Pull to refresh" in features
    has_camera = "Camera" in features
    has_uploads = "File upload" in features
    has_fallback = config.offline_fallback_enabled
    has_bridge = has_share or has_location

    out: list[str] = []
    add = out.append

    # ── imports ──
    add("import 'dart:async';")
    if has_downloads:
        add("import 'dart:io';")
    add("")
    add("import 'package:flutter/material.dart';")
    add("import 'package:flutter/services.dart';")
    add("import 'package:flutter_inappwebview/flutter_inappwebview.dart';")
    add("import 'package:url_launcher/url_launcher.dart';")
    if has_share:
        add("import 'package:share_plus/share_plus.dart';")
    if has_location:
        add("import 'package:geolocator/geolocator.dart';")
    if has_downloads:
        add("import 'package:open_filex/open_filex.dart';")
        add("import 'package:path_provider/path_provider.dart';")
    if has_deep_links:
        add("import 'package:app_links/app_links.dart';")
    add("")

    # ── constants ──
    domains = [d.lower() for d in config.allowed_domains]
    add(f"const homeUrl = {dart_string(config.website_url)};")
    add(f"const allowedDomains = <String>{json.dumps(domains)};")
    add(f"const requireHttps = {_dart_bool(config.require_https)};")
    add(f"const externalLinkBehavior = {dart_string(config.external_link_behavior)};")
    if has_deep_links:
        add(f"const deepLinkScheme = {dart_string(deep_link_scheme(config))};")
    add("")

    if has_fallback:
        add(_OFFLINE_ERROR_TYPES)

    # ── entry point ──
    add(_MAIN_FUNCTION)
    add(_APP_WIDGET.replace("__TITLE__", dart_string(config.display_name)))
    add(_SCREEN_HEADER)

    if has_fallback:
        add(
            "  String? errorTitle;\n"
            "  String? errorMessage;\n"
            "  String? currentUrl;\n"
            "  bool errorIsOffline = false;"
        )
    add("")

    # ── initState ──
    add("  @override")
    add("  void initState() {")
    add("    super.initState();")
    if has_pull_refresh:
        add("    pullToRefreshController = PullToRefreshController(")
        add("      onRefresh: () async => controller?.reload(),")
        add("    );")
    if has_deep_links:
        add("    _listenForDeepLinks();")
    add("  }")
    add("")

    if has_deep_links:
        add(_DEEP_LINKS)

    add(_LOAD_TIMEOUT)
    add(_FINISH_LOAD)
    add(_finish_failed_load(has_fallback))

    if has_fallback:
        add(_FAILURE_CLASSIFIERS)

    add(_ALLOWED_HOST)

    if has_deep_links:
        add(_ALLOWED_WEB_URI)

    add(_DECIDE_NAVIGATION)

    # `_load` is only reachable from deep links or the retry buttons. Emitting
    # it otherwise leaves dead code, which fails the generated project's own
    # flutter_lints run.
    if has_deep_links or has_fallback:
        add(_load_method(has_fallback))

    add(_HANDLE_BACK)
    add(_page_policies(has_uploads))

    if has_bridge:
        add(_bridge(has_share, has_location))

    if has_downloads:
        add(_DOWNLOAD)

    add(_SHOW_MESSAGE)
    add(
        _build_method(
            config,
            splash_asset=splash_asset,
            has_fallback=has_fallback,
            has_bridge=has_bridge,
            has_downloads=has_downloads,
            has_camera=has_camera,
        )
    )
    add(_DISPOSE)

    if has_fallback:
        add(_ERROR_VIEW)

    return "\n".join(out).rstrip() + "\n"


def _dart_bool(value: bool) -> str:
    return "true" if value else "false"


_OFFLINE_ERROR_TYPES = """\
/// Error values that mean the device could not reach the network at all, as
/// opposed to the server answering with a failure. The two need different
/// advice: one is "check your connection", the other is not.
const offlineErrorTypes = <String>{
  'NOT_CONNECTED_TO_INTERNET',
  'HOST_LOOKUP',
  'CANNOT_CONNECT_TO_HOST',
  'NETWORK_CONNECTION_LOST',
  'SERVER_UNREACHABLE',
  'CANNOT_LOAD_FROM_NETWORK',
  'TIMEOUT',
};
"""

_MAIN_FUNCTION = """\
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    systemNavigationBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.dark,
    systemNavigationBarIconBrightness: Brightness.dark,
  ));
  runApp(const GeneratedWebViewApp());
}
"""

_APP_WIDGET = """\
class GeneratedWebViewApp extends StatelessWidget {
  const GeneratedWebViewApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: __TITLE__,
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.grey),
      ),
      home: const WebViewScreen(),
    );
  }
}
"""

_SCREEN_HEADER = """\
class WebViewScreen extends StatefulWidget {
  const WebViewScreen({super.key});

  @override
  State<WebViewScreen> createState() => _WebViewScreenState();
}

class _WebViewScreenState extends State<WebViewScreen> {
  InAppWebViewController? controller;
  PullToRefreshController? pullToRefreshController;
  Timer? loadTimeout;
  StreamSubscription<Uri>? deepLinkSubscription;
  bool showSplash = true;
  double progress = 0;"""

_DEEP_LINKS = """\
  void _listenForDeepLinks() {
    final appLinks = AppLinks();
    deepLinkSubscription = appLinks.uriLinkStream.listen(_handleIncomingLink);
  }

  Future<void> _handleIncomingLink(Uri uri) async {
    final target = uri.scheme == deepLinkScheme
        ? Uri.parse(homeUrl).replace(path: uri.path, query: uri.query)
        : uri;
    if (_isAllowedWebUri(target)) {
      await _load(target);
    }
  }
"""

_LOAD_TIMEOUT = """\
  void _startLoadTimeout() {
    loadTimeout?.cancel();
    loadTimeout = Timer(const Duration(seconds: 20), () {
      if (!mounted || progress >= 1) {
        return;
      }
      _finishFailedLoad(
        title: 'This is taking too long',
        message: 'The site did not respond in time. '
            'Check your connection and try again.',
        offline: true,
      );
    });
  }
"""

_FINISH_LOAD = """\
  void _finishLoad() {
    loadTimeout?.cancel();
    pullToRefreshController?.endRefreshing();
    if (mounted) {
      setState(() {
        showSplash = false;
        progress = 1;
      });
    }
  }
"""


def _finish_failed_load(has_fallback: bool) -> str:
    body = [
        "  void _finishFailedLoad({",
        "    required String title,",
        "    required String message,",
        "    required bool offline,",
        "  }) {",
        "    loadTimeout?.cancel();",
        "    pullToRefreshController?.endRefreshing();",
        "    if (mounted) {",
        "      setState(() {",
        "        showSplash = false;",
        "        progress = 1;",
    ]
    if has_fallback:
        body += [
            "        errorTitle = title;",
            "        errorMessage = message;",
            "        errorIsOffline = offline;",
        ]
    body += ["      });", "    }", "  }", ""]
    return "\n".join(body)


_FAILURE_CLASSIFIERS = """\
  /// Turns a transport-level failure into a message a normal user can act on.
  void _failFromError(WebResourceError error) {
    // Compared as a string rather than against the enum constants: those are
    // `static final` in flutter_inappwebview, so a const set of them will not
    // compile, and the string values are stable across package versions.
    final offline = offlineErrorTypes.contains(error.type.toValue());
    _finishFailedLoad(
      title: offline ? 'You appear to be offline' : 'Something went wrong',
      message: offline
          ? 'Check your internet connection and try again.'
          : 'The page could not be loaded. Please try again.',
      offline: offline,
    );
  }

  /// Turns an HTTP status code into a message a normal user can act on.
  void _failFromStatus(int? statusCode) {
    final code = statusCode ?? 0;
    if (code == 404 || code == 410) {
      _finishFailedLoad(
        title: 'Page not found',
        message: 'That page no longer exists. Return to the home page to '
            'keep going.',
        offline: false,
      );
      return;
    }
    if (code == 401 || code == 403) {
      _finishFailedLoad(
        title: 'Access denied',
        message: 'You do not have permission to view this page. Sign in and '
            'try again.',
        offline: false,
      );
      return;
    }
    _finishFailedLoad(
      title: 'Something went wrong',
      message: code >= 500
          ? 'The server is having trouble right now. Please try again in a '
              'moment.'
          : 'The page could not be loaded. Please try again.',
      offline: false,
    );
  }

  void _retry() {
    _load(Uri.parse(currentUrl ?? homeUrl));
  }

  void _goHome() {
    _load(Uri.parse(homeUrl));
  }
"""

_ALLOWED_HOST = """\
  bool _isAllowedHost(String host) {
    final normalized = host.toLowerCase();
    return allowedDomains.any(
      (domain) => normalized == domain || normalized.endsWith('.$domain'),
    );
  }
"""

_ALLOWED_WEB_URI = """\
  bool _isAllowedWebUri(Uri uri) {
    if (uri.scheme != 'http' && uri.scheme != 'https') {
      return false;
    }
    if (requireHttps && uri.scheme != 'https') {
      return false;
    }
    return _isAllowedHost(uri.host);
  }
"""

# The behaviour names match config.EXTERNAL_LINK_BEHAVIOURS exactly. They differ
# from the desktop builder's ('inApp' / 'externalBrowser'), so this is one of the
# few places the port is deliberately not a transcription.
_DECIDE_NAVIGATION = """\
  Future<NavigationActionPolicy> _decideNavigation(Uri uri) async {
    if (uri.scheme != 'http' && uri.scheme != 'https') {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
      return NavigationActionPolicy.CANCEL;
    }
    if (requireHttps && uri.scheme != 'https') {
      _showMessage('Blocked insecure HTTP navigation.');
      return NavigationActionPolicy.CANCEL;
    }
    if (_isAllowedHost(uri.host) || externalLinkBehavior == 'webview') {
      return NavigationActionPolicy.ALLOW;
    }
    if (externalLinkBehavior == 'browser') {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    } else {
      _showMessage('Blocked link outside the allowed domains.');
    }
    return NavigationActionPolicy.CANCEL;
  }
"""


def _load_method(has_fallback: bool) -> str:
    clear = (
        "      errorTitle = null;\n      errorMessage = null;\n"
        if has_fallback
        else ""
    )
    return (
        "  Future<void> _load(Uri uri) async {\n"
        "    setState(() {\n"
        "      progress = 0;\n"
        f"{clear}"
        "    });\n"
        "    _startLoadTimeout();\n"
        "    await controller?.loadUrl(\n"
        "      urlRequest: URLRequest(url: WebUri(uri.toString())),\n"
        "    );\n"
        "  }\n"
    )


_HANDLE_BACK = """\
  Future<void> _handleBack() async {
    if (await controller?.canGoBack() == true) {
      await controller?.goBack();
      return;
    }
    SystemNavigator.pop();
  }
"""


def _page_policies(has_uploads: bool) -> str:
    if has_uploads:
        return "  Future<void> _applyPagePolicies() async {}\n"
    # The picker cannot be disabled at the WebView level, so file inputs are
    # disabled in the page instead. The observer catches inputs added later by
    # scripts, which a one-off pass would miss.
    return """\
  Future<void> _applyPagePolicies() async {
    await controller?.evaluateJavascript(source: \"\"\"
      (() => {
        const disable = (root) => root.querySelectorAll('input[type="file"]')
          .forEach((input) => input.disabled = true);
        disable(document);
        new MutationObserver(() => disable(document)).observe(
          document.documentElement,
          { childList: true, subtree: true },
        );
      })();
    \"\"\");
  }
"""


def _bridge(has_share: bool, has_location: bool) -> str:
    parts = ["""\
  /// Only pages on an allowed HTTPS origin may call into the app. Without this
  /// an injected script or a redirect could reach the share sheet and location.
  Future<bool> _bridgeOriginAllowed() async {
    final current = await controller?.getUrl();
    final uri = current == null ? null : Uri.tryParse(current.toString());
    return uri != null && uri.scheme == 'https' && _isAllowedHost(uri.host);
  }

  Future<Object?> _handleBridge(List<dynamic> arguments) async {
    if (!await _bridgeOriginAllowed()) {
      return {'status': 'denied', 'message': 'Origin is not allowed.'};
    }
    final payload = arguments.isNotEmpty && arguments.first is Map
        ? Map<String, dynamic>.from(arguments.first as Map)
        : <String, dynamic>{};
    // The origin check above was awaited, so the widget may already be gone.
    // Handlers below reach for `context`, and using it after an async gap
    // without this guard is both a real crash and an analyzer error in the
    // generated project's own lint run.
    if (!mounted) {
      return {'status': 'denied', 'message': 'The app is no longer visible.'};
    }
    final action = payload['action'];
    if (action == 'ping') {
      return {'status': 'ok'};
    }
"""]
    if has_share:
        parts.append("""\
    if (action == 'share') {
      final box = context.findRenderObject() as RenderBox?;
      await SharePlus.instance.share(
        ShareParams(
          text: (payload['text'] ?? '').toString(),
          sharePositionOrigin: box == null
              ? null
              : box.localToGlobal(Offset.zero) & box.size,
        ),
      );
      return {'status': 'ok'};
    }
""")
    if has_location:
        parts.append("""\
    if (action == 'getLocation') {
      var permission = await Geolocator.checkPermission();
      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
      }
      if (permission == LocationPermission.denied ||
          permission == LocationPermission.deniedForever) {
        return {'status': 'denied'};
      }
      final position = await Geolocator.getCurrentPosition();
      return {
        'status': 'ok',
        'latitude': position.latitude,
        'longitude': position.longitude,
      };
    }
""")
    parts.append("    return {'status': 'unsupported', 'action': action};\n  }\n")
    return "".join(parts)


_DOWNLOAD = r"""  Future<void> _download(DownloadStartRequest request) async {
    try {
      final uri = Uri.parse(request.url.toString());
      if (!_isAllowedHost(uri.host)) {
        _showMessage('Blocked download from an unapproved domain.');
        return;
      }
      final client = HttpClient();
      final httpRequest = await client.getUrl(uri);
      final cookies = await CookieManager.instance().getCookies(url: request.url);
      if (cookies.isNotEmpty) {
        httpRequest.headers.set(
          HttpHeaders.cookieHeader,
          cookies.map((cookie) => '${cookie.name}=${cookie.value}').join('; '),
        );
      }
      final response = await httpRequest.close();
      final directory = await getApplicationDocumentsDirectory();
      final rawName = request.suggestedFilename ??
          (uri.pathSegments.isEmpty ? 'download' : uri.pathSegments.last);
      // A server-supplied filename reaches the filesystem, so path separators
      // and reserved characters are stripped rather than trusted.
      final fileName = rawName.replaceAll(RegExp(r'[<>:"/\\|?*]'), '_');
      final file = File('${directory.path}/$fileName');
      await response.pipe(file.openWrite());
      client.close();
      _showMessage('Downloaded $fileName');
      await OpenFilex.open(file.path);
    } catch (error) {
      _showMessage('Download failed: $error');
    }
  }
"""

_SHOW_MESSAGE = """\
  void _showMessage(String message) {
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(message)),
      );
    }
  }
"""


def _build_method(
    config: AppConfig,
    *,
    splash_asset: str | None,
    has_fallback: bool,
    has_bridge: bool,
    has_downloads: bool,
    has_camera: bool,
) -> str:
    splash = (
        "const SizedBox.expand()"
        if not splash_asset
        else (
            "Image.asset(\n"
            f"                  {dart_string(splash_asset)},\n"
            "                  fit: BoxFit.cover,\n"
            "                  width: double.infinity,\n"
            "                  height: double.infinity,\n"
            "                )"
        )
    )
    user_agent = (
        "null" if not config.custom_user_agent else dart_string(config.custom_user_agent)
    )
    cache_mode = (
        "CacheMode.LOAD_DEFAULT" if config.cache_enabled else "CacheMode.LOAD_NO_CACHE"
    )

    out: list[str] = []
    add = out.append
    add("  @override")
    add("  Widget build(BuildContext context) {")
    add("    return PopScope(")
    add("      canPop: false,")
    add("      onPopInvokedWithResult: (didPop, result) async {")
    add("        if (!didPop) {")
    add("          await _handleBack();")
    add("        }")
    add("      },")
    add("      child: Scaffold(")
    add("        backgroundColor: Theme.of(context).colorScheme.surface,")
    add("        body: SafeArea(")
    add("          child: Stack(")
    add("            fit: StackFit.expand,")
    add("            children: [")
    add("              InAppWebView(")
    add("                initialUrlRequest: URLRequest(url: WebUri(homeUrl)),")
    add("                pullToRefreshController: pullToRefreshController,")
    add("                initialSettings: InAppWebViewSettings(")
    add(f"                  javaScriptEnabled: {_dart_bool(config.javascript_enabled)},")
    add(f"                  domStorageEnabled: {_dart_bool(config.dom_storage_enabled)},")
    add(f"                  userAgent: {user_agent},")
    add("                  useShouldOverrideUrlLoading: true,")
    add(f"                  useOnDownloadStart: {_dart_bool(has_downloads)},")
    add(f"                  cacheEnabled: {_dart_bool(config.cache_enabled)},")
    add(f"                  cacheMode: {cache_mode},")
    add("                ),")
    add("                onWebViewCreated: (value) {")
    add("                  controller = value;")
    if has_bridge:
        add("                  value.addJavaScriptHandler(")
        add("                    handlerName: 'CissyBridge',")
        add("                    callback: _handleBridge,")
        add("                  );")
    add("                  _startLoadTimeout();")
    add("                },")
    add("                shouldOverrideUrlLoading: (_, action) async {")
    add("                  final target = action.request.url;")
    add("                  final uri = target == null")
    add("                      ? null")
    add("                      : Uri.tryParse(target.toString());")
    add("                  return uri == null")
    add("                      ? NavigationActionPolicy.CANCEL")
    add("                      : _decideNavigation(uri);")
    add("                },")
    add("                onLoadStart: (_, url) {")
    add("                  setState(() {")
    add("                    progress = 0;")
    if has_fallback:
        add("                    currentUrl = url?.toString() ?? currentUrl;")
        add("                    errorTitle = null;")
        add("                    errorMessage = null;")
    add("                  });")
    add("                  _startLoadTimeout();")
    add("                },")
    add("                onProgressChanged: (_, value) {")
    add("                  if (mounted) {")
    add("                    setState(() => progress = value / 100);")
    add("                  }")
    add("                },")
    add("                onLoadStop: (_, __) async {")
    add("                  await _applyPagePolicies();")
    add("                  _finishLoad();")
    add("                },")
    add("                onReceivedError: (_, request, error) {")
    add("                  if (request.isForMainFrame == true) {")
    if has_fallback:
        add("                    _failFromError(error);")
    else:
        add("                    _finishFailedLoad(")
        add("                      title: 'Something went wrong',")
        add("                      message: 'The page could not be loaded.',")
        add("                      offline: false,")
        add("                    );")
    add("                  }")
    add("                },")
    add("                onReceivedHttpError: (_, request, response) {")
    add("                  if (request.isForMainFrame == true) {")
    if has_fallback:
        add("                    _failFromStatus(response.statusCode);")
    else:
        add("                    _finishFailedLoad(")
        add("                      title: 'Something went wrong',")
        add("                      message: 'The page could not be loaded.',")
        add("                      offline: false,")
        add("                    );")
    add("                  }")
    add("                },")
    if has_camera:
        add("                onPermissionRequest: (_, request) async {")
        add("                  final current = await controller?.getUrl();")
        add("                  final uri = current == null")
        add("                      ? null")
        add("                      : Uri.tryParse(current.toString());")
        add("                  final allowed = uri != null &&")
        add("                      uri.scheme == 'https' &&")
        add("                      _isAllowedHost(uri.host);")
        add("                  return PermissionResponse(")
        add("                    resources: request.resources,")
        add("                    action: allowed")
        add("                        ? PermissionResponseAction.GRANT")
        add("                        : PermissionResponseAction.DENY,")
        add("                  );")
        add("                },")
    if has_downloads:
        add("                onDownloadStartRequest: (_, request) => _download(request),")
    add("              ),")
    if has_fallback:
        add("              if (errorTitle != null)")
        add("                _ErrorView(")
        add("                  title: errorTitle!,")
        add("                  message: errorMessage ?? '',")
        add("                  isOffline: errorIsOffline,")
        add("                  onRetry: _retry,")
        add("                  onHome: _goHome,")
        add("                ),")
    add("              if (showSplash)")
    add("                ColoredBox(")
    add("                  color: Colors.transparent,")
    add(f"                  child: {splash},")
    add("                ),")
    add("            ],")
    add("          ),")
    add("        ),")
    add("      ),")
    add("    );")
    add("  }")
    return "\n".join(out) + "\n"


_DISPOSE = """\
  @override
  void dispose() {
    loadTimeout?.cancel();
    deepLinkSubscription?.cancel();
    super.dispose();
  }
}
"""

_ERROR_VIEW = """\
/// Shown instead of the browser's own failure page, so a broken load still
/// looks like this app and always offers a way forward.
class _ErrorView extends StatelessWidget {
  const _ErrorView({
    required this.title,
    required this.message,
    required this.isOffline,
    required this.onRetry,
    required this.onHome,
  });

  final String title;
  final String message;
  final bool isOffline;
  final VoidCallback onRetry;
  final VoidCallback onHome;

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).colorScheme;
    return ColoredBox(
      color: colors.surface,
      child: Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(
                isOffline
                    ? Icons.wifi_off_rounded
                    : Icons.error_outline_rounded,
                size: 52,
                color: colors.onSurfaceVariant,
              ),
              const SizedBox(height: 20),
              Text(
                title,
                textAlign: TextAlign.center,
                style: Theme.of(context).textTheme.titleLarge,
              ),
              const SizedBox(height: 10),
              Text(
                message,
                textAlign: TextAlign.center,
                style: TextStyle(
                  color: colors.onSurfaceVariant,
                  height: 1.45,
                ),
              ),
              const SizedBox(height: 26),
              FilledButton.icon(
                onPressed: onRetry,
                icon: const Icon(Icons.replay_rounded, size: 18),
                label: const Text('Try again'),
              ),
              const SizedBox(height: 6),
              TextButton(
                onPressed: onHome,
                child: const Text('Go to home page'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
"""


# ── android ──────────────────────────────────────────────────────────────


def android_manifest(config: AppConfig) -> str:
    features = set(config.features)
    label = escape(config.display_name, quote=True)
    host = _host_of(config.website_url)

    permissions = ['    <uses-permission android:name="android.permission.INTERNET" />']
    if "Camera" in features:
        permissions.append(
            '    <uses-permission android:name="android.permission.CAMERA" />'
        )
    if "Location" in features:
        permissions.append(
            '    <uses-permission '
            'android:name="android.permission.ACCESS_COARSE_LOCATION" />'
        )
        permissions.append(
            '    <uses-permission '
            'android:name="android.permission.ACCESS_FINE_LOCATION" />'
        )

    deep_link_filter = ""
    if "Deep links" in features and host:
        deep_link_filter = f"""
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="https" android:host="{host}"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="{deep_link_scheme(config)}"/>
            </intent-filter>"""

    cleartext = "true" if not config.require_https else "false"

    return f"""<manifest xmlns:android="http://schemas.android.com/apk/res/android">
{chr(10).join(permissions)}
    <application
        android:label="{label}"
        android:name="${{applicationName}}"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="{cleartext}">
        <activity
            android:name="{config.android_package_id}.MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:taskAffinity=""
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>{deep_link_filter}
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
"""


def gradle_properties() -> str:
    """Gradle settings tuned for a small, occasionally-used build box.

    The daemon holds well over a gigabyte between builds, which is wasted on a
    server that builds twice a week and has 4 GB to work with. Turning it off
    costs about twenty seconds of JVM startup per build.
    """
    return (
        "org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m\n"
        "org.gradle.daemon=false\n"
        "org.gradle.parallel=false\n"
        "android.useAndroidX=true\n"
        "android.enableJetifier=true\n"
    )


def main_activity(config: AppConfig) -> str:
    return f"""package {config.android_package_id}

import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity()
"""


# ── ios ──────────────────────────────────────────────────────────────────


def ios_usage_descriptions(config: AppConfig) -> dict[str, str]:
    """Info.plist reasons for every permission the app can request.

    A missing one is not a warning — iOS terminates the app the moment the
    permission is requested, and App Store review rejects the build.
    """
    features = set(config.features)
    values: dict[str, str] = {}
    if "Camera" in features:
        values["NSCameraUsageDescription"] = config.permission_description("camera")
    if "Camera" in features or "File upload" in features:
        values["NSPhotoLibraryUsageDescription"] = config.permission_description(
            "photos"
        )
    if "Location" in features:
        values["NSLocationWhenInUseUsageDescription"] = config.permission_description(
            "location"
        )
    return values


def _host_of(url: str) -> str:
    from urllib.parse import urlparse

    return (urlparse(url).hostname or "").lower()
